apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-http
spec:
  selector:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
