apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9101'
    spec:
      containers:
      - name: backend
        image: amenyelokb/library_backend:latest
        ports:
        - containerPort: 8082
        env:
        - name: MYSQL_HOST
          value: "localhost"  
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"  
        - name: MYSQL_PASSWORD
          value: ""  
        - name: MYSQL_DB
          value: "reactlibrarydatabase"  
