apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # external port
      targetPort: 8081  # container's port
  type: LoadBalancer  # Use NodePort or ClusterIP for internal services
