apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 5  # specify the number of instances
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amenyelokb/library_backend:latest  # specify your Docker image
        ports:
        - containerPort: 8081  # replace with your container's port
