apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: library-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
      - name: backend-deployment
        image: amenyelokb/library_backend:latest
        ports:
        - containerPort: 8082
       