apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # external port
      targetPort: 5173  # container's port
  type: LoadBalancer  # Use NodePort or ClusterIP for internal services
