apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80  # external port
      targetPort: 5173  # container's port
  selector:
    app: frontend
  
