apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9101'
    spec:
      containers:
      - name: frontend
        image: amenyelokb/react-library:latest
        ports:
        - containerPort: 5173
